### ISSUE TITLE
请问lab_env.xml文件的参数都是自己手写么？

### ISSUE THREAD

**Issue by zhujianing** [cxy1997/Robotiq-UR5#1]
请问lab_env.xml文件的参数都是自己手写么？我要做一个自由度小点的机械臂，但不知道这些参数该怎么配置，请问是用软件生成的还是自己配制，谢谢。

`<body name="wrist2_link" pos="0 0.093 0">
                                <inertial pos="0 0 0" quat="0.5 0.5 -0.5 0.5" mass="1.219" diaginertia="0.21942 0.111173 0.111173" />
                                <geom name="wrist2_mesh" type="mesh" mesh="wrist2" material="RobMat" />
                                <geom name="wrist2_cap" type="cylinder" pos="0 0 -0.045" quat="0.707107 0 0 0.707107" size="0.04 0.015" rgba="0.596 0.96 1 1" material="RobMat" contype="0" conaffinity="0" />
                                <joint name="joint5" pos="0 0 0" axis="0 0 1" />`

类似quat，size这样的参数

**Comment by cxy1997** [comment]
机械臂部分的参数来源是：
[http://hades.mech.northwestern.edu/images/4/49/UR5-URDF.pdf](http://hades.mech.northwestern.edu/images/4/49/UR5-URDF.pdf)
为了方便使用，xml格式从URDF转成了MJCF，用的MuJoCo内置函数：
[http://www.mujoco.org/book/reference.html#mj_saveLastXML](http://www.mujoco.org/book/reference.html#mj_saveLastXML)
然后，Meshes的来源是：
[https://github.com/ros-industrial/universal_robot](https://github.com/ros-industrial/universal_robot)
机械臂部分的参数都是查到的，夹具部分的参数有部分是手调的，quat的定义可以参考：
[http://www.mujoco.org/book/modeling.html#COrientation](http://www.mujoco.org/book/modeling.html#COrientation)

希望这些能帮到你
