### ISSUE TITLE
机械臂控制

### ISSUE THREAD

**Issue by zhouxingqun** [cxy1997/Robotiq-UR5#2]
你好，在仿真环境中可以直接控制机械臂末端的空间位置吗？还是只能控制关节角度？如果我需要机械臂达到某个空间坐标，需要自己计算对应的关节角度吗？

**Comment by cxy1997** [comment]
可以的，下面这个函数是根据关节角度计算空间三维坐标，你可以根据它的参数反算一下
https://github.com/cxy1997/Robotiq-UR5/blob/master/environment.py#L214

**Comment by zhouxingqun** [comment]
> 可以的，下面这个函数是根据关节角度计算空间三维坐标，你可以根据它的参数反算一下
> https://github.com/cxy1997/Robotiq-UR5/blob/master/environment.py#L214

谢谢！
